### ISSUE TITLE
"libtoolize not found" - linux dependency

### ISSUE THREAD

**Issue by mixmix** [pfrazee/beaker#54]
have hit this error a few times : 

```bash
make: Leaving directory '/home/mix/projects/SSBC/beaker/app/node_modules/sqlite3/build'

> sodium-prebuilt@1.0.22 install /home/mix/projects/SSBC/beaker/app/node_modules/sodium-prebuilt
> prebuild --install --preinstall make

./autogen.sh: 13: ./autogen.sh: libtoolize: not found
Makefile:8: recipe for target 'configure' failed
make: *** [configure] Error 127
prebuild ERR! build Error: make  failed with exit code 2
prebuild ERR! build     at Object.exports.spawnFailed (/home/mix/projects/SSBC/beaker/app/node_modules/prebuild/error.js:31:10)
prebuild ERR! build     at ChildProcess.<anonymous> (/home/mix/projects/SSBC/beaker/app/node_modules/prebuild/util.js:113:14)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12
```

have run ` burnthemall`
I think there's a dependency required : `libtool` in ubuntu

sorry to following is thorough and a bit tedious.

---

```
sudo apt-get install libtool
npm run burnthemall
```

lead to:
```bash
libtoolize:   error: One of these is required:
libtoolize:                 gm4 gnum4 m4
```

ran:
```
sudo apt-get install m4
npm run burnthemall
```

Got:
```
autogen.sh: aclocal: not found
```

ran:
```
sudo apt-get install automake
npm run burnthemall
```
(I thought that was already installed)

works

**Comment by pfrazee** [comment]
Thanks. I'll update the docs to mention these.

**Comment by mixmix** [comment]
It could just be automake...
