### ISSUE TITLE
Cannot find module `...sqlite3/lib/binding/.../node_sqlite3.node`

### ISSUE THREAD

**Issue by poga** [pfrazee/beaker#79]
Operation System:
OSX 10.11.6
Beaker Version:
current master `34b86e7672c10aff466dbd6fee03cbfd9d538b7c`

```
$ npm start

> @ start /Users/poga/projects/beaker
> gulp start

[12:37:13] Using gulpfile ~/projects/beaker/gulpfile.js
[12:37:13] Starting 'start'...
[12:37:13] Finished 'start' after 6.05 ms
App threw an error during load
Error: Cannot find module '/Users/poga/projects/beaker/app/node_modules/sqlite3/lib/binding/electron-v1.3-darwin-x64/node_sqlite3.node'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/Users/poga/projects/beaker/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/poga/projects/beaker/app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

I tried `npm run bunthemall` but the problem persists.

Any idea if I missed something?

**Comment by poga** [comment]
nvm I forgot to run `npm run rebuild`.
